// Generated by https://quicktype.io

export interface InterfazBitacora {
    resutls: Resutl[];
}

export interface Resutl {
    idLog:       number;
    description: string;
    date:        string;
    action:      string;
    user_name:   string;
}

