
// Generated by https://quicktype.io


export interface InterfazCliente {
    customers: Customer[];
}

export interface Customer {
    idCustomer?:              number;
    full_name?:               string;
    phone?:                   string;
    email?:                   string;
    housing?:                 string;
    street?:                  string;
    postal_code?:             number;
    status?:                  boolean;
    idMunicipality_Customer?: number;
    idState_Customer?:        number;
}





